# Generated by go2rpm 1
%bcond_without check

# https://github.com/jcmturner/dnsutils/v2
%global goipath         github.com/jcmturner/dnsutils/v2
Version:                2.0.0

%gometa

%global common_description %{expand:
dnsutils Go module}

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        ASL 2.0

URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Apr 24 08:34:33 CEST 2020 Martin Sehnoutka <msehnout@redhat.com> - 2.0.0-1
- Initial package

