# Generated by go2rpm 1
%bcond_without check

# https://github.com/jcmturner/goidentity/v6
%global goipath         github.com/jcmturner/goidentity/v6
Version:                6.0.1

%gometa

%global common_description %{expand:
Standard interface for holding authenticated identities and their attributes.}

%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        ASL 2.0

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/hashicorp/go-uuid)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Apr 24 08:37:18 CEST 2020 Martin Sehnoutka <msehnout@redhat.com> - 6.0.1-1
- Initial package

