# Generated by go2rpm 1
%bcond_without check

# https://github.com/jcmturner/rpc/v2
%global goipath         github.com/jcmturner/rpc/v2
Version:                2.0.2

%gometa

%global common_description %{expand:
Remote Procedure Call libraries.}

%global godocs          examples README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        ASL 2.0

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/net/http2/hpack)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

Provides:       golang(github.com/jcmturner/rpc/v2/ndr)
Provides:       golang(github.com/jcmturner/rpc/v2/mstypes)

%description
%{common_description}

%gopkg

%prep
%setup -n rpc-%{version}
rm -rf examples
rm -rf ndr
rm -rf mstypes
mv v2/* .
%goprep -e

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Apr 24 08:41:20 CEST 2020 Martin Sehnoutka <msehnout@redhat.com> - 2.0.2-1
- Initial package

