# Generated by go2rpm 1
%bcond_without check

# https://github.com/jcmturner/gokrb5/v8
%global goipath         github.com/jcmturner/gokrb5/v8
Version:                8.3.0

%gometa

%global common_description %{expand:
Pure Go Kerberos library for clients and services.}

%global godocs          examples USAGE.md README.md gssapi/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        ASL 2.0

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/hashicorp/go-uuid)
BuildRequires:  golang(github.com/jcmturner/aescts/v2)
BuildRequires:  golang(github.com/jcmturner/dnsutils/v2)
BuildRequires:  golang(github.com/jcmturner/gofork/encoding/asn1)
BuildRequires:  golang(github.com/jcmturner/gofork/x/crypto/pbkdf2)
BuildRequires:  golang(github.com/jcmturner/goidentity/v6)
BuildRequires:  golang(github.com/jcmturner/rpc/v2/mstypes)
BuildRequires:  golang(github.com/jcmturner/rpc/v2/ndr)
BuildRequires:  golang(golang.org/x/crypto/md4)
BuildRequires:  golang(golang.org/x/crypto/pbkdf2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/gorilla/sessions)
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%setup -n gokrb5-%{version}
ls | grep -v v8 | xargs rm -rf
mv v8/* .
%goprep -e

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Apr 24 13:55:36 CEST 2020 Martin Sehnoutka <msehnout@redhat.com> - 8.3.0-1
- Initial package

